[project]
name = "mlops-real-estate-valuation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "playwright>=1.40.0",
    "pandas>=2.2.0",
]
